main: com.modtools.ak.Main
name: ModTools
author: AnyKwey
version: 2
version-api: 1.8.8

commands:
  mod:
    permission: modtools.command.mod
  gamemode:
    permission: modtools.command.mod
    aliases:
      - gm